@startwbs
skinparam backgroundColor white
skinparam ArrowColor #666666
skinparam defaultFontName Arial

title Catalogo de FACETAS

* FACETAS
** Comerciales
*** Vendible
*** TienePrecio
*** TieneReglas
*** EsAddon
*** EsServicioCompuesto
** Operativas
*** RequiereInfra
*** RequierePersonal
*** RequiereConsumible
*** RequiereEquipamiento
*** RequiereLocacion
** Temporales
*** Agendable
*** RequiereHorario
*** RequiereDuracion
*** TieneVentanaHoraria
** Cuantitativas
*** RequierePax
*** RequiereCantidad
*** EsUnitario
*** EsPorPersona
*** EsPorTiempo
** Disponibilidad
*** TieneCapacidad
*** TieneCupo
*** RequiereAnticipacion
*** DependeDeOtroItem
@endwbs
