/**
 * csvSeed.js — Node.js-only utility for loading real CSV data into SEED_DATA format.
 *
 * Usage (Node.js / vitest only — not for browser):
 *
 *   import { loadSeedFromCsvDir } from './csvSeed.js';
 *   const seed = loadSeedFromCsvDir('./data/init');
 *   const db = createDatabase({ seed });
 *
 * The CSV files are expected to already use the exact field names from Config_Schema.js.
 *
 * Adjustments applied automatically:
 *   - REGLAS_NEGOCIO: adds ID_Componente: null (field absent from CSV)
 *   - REGLAS_NEGOCIO: Condicion_JSON / Payload_JSON parsed from JSON strings to objects
 *   - Boolean strings ('true'/'false') → actual booleans
 *   - Numeric fields → numbers (empty string → null)
 *   - Nullable FK fields (empty string → null)
 *
 * NOTE: The REGLAS_NEGOCIO conditions use `linea.ID_Item` / `linea._pax` variable paths
 * (generated by the V1 migration tool). The new Item domain uses `itemId` / `pax` paths.
 * When wiring rules to the new RulesCoordinator, update condition variable paths accordingly.
 */

import fs from 'node:fs';
import path from 'node:path';

// ── CSV parser ──────────────────────────────────────────────────────────────

function stripBom(s) {
  return s && s.charCodeAt(0) === 0xfeff ? s.slice(1) : s;
}

function parseCsvLine(line) {
  const cells = [];
  let cur = '';
  let inQ = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    const nx = line[i + 1];
    if (ch === '"') {
      if (inQ && nx === '"') { cur += '"'; i++; }
      else inQ = !inQ;
      continue;
    }
    if (ch === ',' && !inQ) { cells.push(cur); cur = ''; continue; }
    cur += ch;
  }
  cells.push(cur);
  return cells;
}

function parseCsv(content) {
  const lines = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n').filter(l => l.trim());
  if (!lines.length) return [];
  const headers = parseCsvLine(stripBom(lines[0])).map(h => h.trim());
  return lines.slice(1).map(line => {
    const vals = parseCsvLine(line);
    const row = {};
    headers.forEach((h, i) => { row[h] = vals[i] ?? ''; });
    return row;
  });
}

// ── Type coercion helpers ───────────────────────────────────────────────────

function toBool(v) {
  if (v === true || v === false) return v;
  return String(v).toLowerCase() === 'true';
}

function toNum(v) {
  if (v === '' || v == null) return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function toNullable(v) {
  return v === '' || v == null ? null : v;
}

function toJson(v) {
  if (!v || v === '') return null;
  if (typeof v === 'object') return v;
  try { return JSON.parse(v); } catch { return v; }
}

// ── Per-table type maps ─────────────────────────────────────────────────────

function coercePerfil(row) {
  return {
    ID_Perfil_Precio: row.ID_Perfil_Precio,
    Nombre: row.Nombre,
    Costo_Base_Fijo:      toNum(row.Costo_Base_Fijo),
    Costo_Unitario_Pax:   toNum(row.Costo_Unitario_Pax),
    Costo_Unitario_Tiempo:toNum(row.Costo_Unitario_Tiempo),
    Costo_Unitario_Item:  toNum(row.Costo_Unitario_Item),
    Activo:               toBool(row.Activo),
    Updated_At:           row.Updated_At,
  };
}

function coercePerfilInit(row) {
  return {
    ID_Perfil_Init:      row.ID_Perfil_Init,
    Nombre:              row.Nombre,
    Duracion_Min:        toNum(row.Duracion_Min),
    Unidades_Por_Pax:    toNum(row.Unidades_Por_Pax),
    Unidades_Por_Hora:   toNum(row.Unidades_Por_Hora),
    Minutos_Por_Usuario: toNum(row.Minutos_Por_Usuario),
    Cantidad_Fija:       toNum(row.Cantidad_Fija),
    Pax_Fijo:            toNum(row.Pax_Fijo),
    Activo:              toBool(row.Activo),
    Updated_At:          row.Updated_At,
  };
}

function coerceCategoria(row) {
  return {
    ID_Categoria:              row.ID_Categoria,
    Nombre:                    row.Nombre,
    ID_Perfil_Precio_Default:  toNullable(row.ID_Perfil_Precio_Default),
    ID_Perfil_Init_Default:    toNullable(row.ID_Perfil_Init_Default),
    Def_Requiere_Pax:          toBool(row.Def_Requiere_Pax),
    Def_Requiere_Cant:         toBool(row.Def_Requiere_Cant),
    Def_Requiere_Tiempo:       toBool(row.Def_Requiere_Tiempo),
    Def_Requiere_Hora:         toBool(row.Def_Requiere_Hora),
    Icono_UI:                  toNullable(row.Icono_UI),
    Activo:                    toBool(row.Activo),
    Updated_At:                row.Updated_At,
  };
}

function coerceItem(row) {
  return {
    ID_Item:                       row.ID_Item,
    Nombre:                        row.Nombre,
    ID_Categoria:                  row.ID_Categoria,
    ID_Perfil_Precio_Override:     toNullable(row.ID_Perfil_Precio_Override),
    ID_Perfil_Init_Override:       toNullable(row.ID_Perfil_Init_Override),
    Default_Glosa:                 toNullable(row.Default_Glosa),
    Activo:                        toBool(row.Activo),
    Updated_At:                    row.Updated_At,
  };
}

function coerceRegla(row) {
  // ID_Componente is absent from the CSV (conditions use JSON-Logic for item targeting).
  // Added here as null so the schema contract is satisfied.
  return {
    ID_Regla:       row.ID_Regla,
    Nombre:         row.Nombre,
    Etapa:          row.Etapa,
    Scope:          row.Scope,
    ID_Componente:  null,
    Tipo_Accion:    row.Tipo_Accion,
    Hook:           toNullable(row.Hook),
    Condicion_JSON: toJson(row.Condicion_JSON),
    Payload_JSON:   toJson(row.Payload_JSON),
    Prioridad:      toNum(row.Prioridad),
    Acumulable:     toBool(row.Acumulable),
    Activo:         toBool(row.Activo),
    Updated_At:     row.Updated_At,
  };
}

function coerceCliente(row) {
  return {
    ID_Cliente:      row.ID_Cliente,
    Nombre_Empresa:  row.Nombre_Empresa,
    RUT:             row.RUT,
    Email:           row.Email,
    Telefono:        toNullable(row.Telefono),
    Updated_At:      row.Updated_At,
  };
}

function coerceComposicion(row) {
  return {
    ID_Composicion: row.ID_Composicion,
    ID_Item_Padre:  row.ID_Item_Padre,
    ID_Item_Hijo:   row.ID_Item_Hijo,
    Cantidad:       toNum(row.Cantidad),
    Tipo_Precio:    row.Tipo_Precio,
    Updated_At:     row.Updated_At,
  };
}

function coerceCotizacion(row) {
  return {
    ID_Cotizacion: row.ID_Cotizacion,
    ID_Cliente:    row.ID_Cliente,
    Estado:        row.Estado,
    Fecha_Evento:  toNullable(row.Fecha_Evento),
    Duracion_Dias: toNum(row.Duracion_Dias),
    Pax_Global:    toNum(row.Pax_Global),
    Updated_At:    row.Updated_At,
  };
}

function coerceLinea(row) {
  return {
    ID_Linea:              row.ID_Linea,
    ID_Cotizacion:         row.ID_Cotizacion,
    ID_Item:               row.ID_Item,
    Estado_Linea:          row.Estado_Linea,
    Dia_Numero:            toNum(row.Dia_Numero),
    Hora_Inicio:           toNullable(row.Hora_Inicio),
    Override_Pax:          toNum(row.Override_Pax),
    Override_Cantidad:     toNum(row.Override_Cantidad),
    Override_Duracion_Min: toNum(row.Override_Duracion_Min),
    Comentarios:           toNullable(row.Comentarios),
    Updated_At:            row.Updated_At,
  };
}

function coerceAjuste(row) {
  return {
    ID_Ajuste:      row.ID_Ajuste,
    ID_Cotizacion:  row.ID_Cotizacion,
    ID_Linea:       row.ID_Linea,
    Tipo_Ajuste:    row.Tipo_Ajuste,
    Valor_Original: toNum(row.Valor_Original),
    Valor_Nuevo:    toNum(row.Valor_Nuevo),
    Motivo:         toNullable(row.Motivo),
    Usuario:        toNullable(row.Usuario),
    Updated_At:     row.Updated_At,
  };
}

function coerceCache(row) {
  return {
    ID_Cotizacion: row.ID_Cotizacion,
    Snapshot_JSON: toJson(row.Snapshot_JSON),
    Updated_At:    row.Updated_At,
  };
}

function coerceHistorial(row) {
  return {
    ID_Log:         row.ID_Log,
    ID_Cotizacion:  row.ID_Cotizacion,
    Timestamp:      row.Timestamp,
    Usuario:        toNullable(row.Usuario),
    Accion:         row.Accion,
    Detalle_Cambio: toJson(row.Detalle_Cambio),
  };
}

// ── Loader ──────────────────────────────────────────────────────────────────

const LOADERS = {
  // Block 1 — Reference data
  CLIENTES:        coerceCliente,
  PERFILES_PRECIO: coercePerfil,
  PERFILES_INICIALIZACION: coercePerfilInit,
  CATEGORIAS:      coerceCategoria,
  ITEM_CATALOGO:   coerceItem,
  COMPOSICION_KIT: coerceComposicion,
  REGLAS_NEGOCIO:  coerceRegla,
  // Block 2 — Transactional data
  COTIZACIONES:         coerceCotizacion,
  LINEA_DETALLE:        coerceLinea,
  AJUSTES_COTIZACION:   coerceAjuste,
  CACHE_COTIZACION:     coerceCache,
  HISTORIAL_COTIZACION: coerceHistorial,
};

function loadTable(dirPath, tableName, coerce) {
  const filePath = path.resolve(dirPath, `${tableName}.csv`);
  if (!fs.existsSync(filePath)) return [];
  const raw = parseCsv(fs.readFileSync(filePath, 'utf8'));
  return raw.map(coerce);
}

/**
 * Load all catalog + config tables from a directory of CSV files.
 * Returns an array in SEED_DATA format: [{ table, records }]
 *
 * @param {string} dirPath - path to directory containing CSV files
 * @param {string[]} [tables] - subset of tables to load (defaults to all supported)
 */
export function loadSeedFromCsvDir(dirPath, tables = Object.keys(LOADERS)) {
  return tables
    .filter(t => LOADERS[t])
    .map(table => ({
      table,
      records: loadTable(dirPath, table, LOADERS[table]),
    }))
    .filter(entry => entry.records.length > 0);
}
