@startuml
title Object Diagram Example

object quotationFlow {
  stage = "basket"
}

object basket {
  selectedDayIndex = 1
}

object day1 {
  dayIndex = 1
}

object itemA {
  itemId = "ITEM_COFFEE_BASICO"
  total = 24000
}

quotationFlow --> basket
basket --> day1
day1 --> itemA
@enduml
