@startuml
title State Diagram Example

[*] --> browse
browse --> client : start quotation
client --> basket : client selected
basket --> validation : validate
validation --> basket : back to edit
validation --> completed : confirm save
completed --> browse : new quotation
@enduml
