@startuml
title ERD Example

entity CLIENTES {
  * ID_Cliente : string
  --
  Nombre : string
  Email : string
}

entity COTIZACIONES {
  * ID_Cotizacion : string
  --
  ID_Cliente : string
  Fecha_Evento : date
}

entity LINEAS_COTIZACION {
  * ID_Linea : string
  --
  ID_Cotizacion : string
  ID_Item : string
  Dia_Numero : int
}

entity ITEM_CATALOGO {
  * ID_Item : string
  --
  Nombre : string
  ID_Categoria : string
}

CLIENTES ||--o{ COTIZACIONES
COTIZACIONES ||--o{ LINEAS_COTIZACION
ITEM_CATALOGO ||--o{ LINEAS_COTIZACION
@enduml
