#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const schemaPath = path.join(root, 'packages', 'database', 'src', 'Config_Schema.js');
const initDir = path.join(root, 'data', 'init');
const outPath = path.join(root, 'bundling', 'generated', 'localInitTables.js');

function extractSchemaObjectLiteral(source) {
  const marker = 'export const DATA_SCHEMA =';
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) {
    throw new Error('DATA_SCHEMA export marker not found in Config_Schema.js');
  }

  const startBrace = source.indexOf('{', markerIndex);
  let depth = 0;
  let endBrace = -1;

  for (let i = startBrace; i < source.length; i += 1) {
    const char = source[i];
    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    if (depth === 0) {
      endBrace = i;
      break;
    }
  }

  if (endBrace === -1) {
    throw new Error('DATA_SCHEMA closing brace not found in Config_Schema.js');
  }

  return source.slice(startBrace, endBrace + 1);
}

function parseCsvLine(line) {
  const cells = [];
  let current = '';
  let inQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    const next = line[index + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        current += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      cells.push(current);
      current = '';
      continue;
    }

    current += char;
  }

  cells.push(current);
  return cells;
}

function parseCsv(content) {
  const normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const lines = normalized.split('\n').filter((line) => line.trim() !== '');
  if (!lines.length) return [];

  const headers = parseCsvLine(lines[0]).map((value) => String(value || '').trim());
  const rows = [];

  for (let i = 1; i < lines.length; i += 1) {
    const values = parseCsvLine(lines[i]);
    const row = {};

    headers.forEach((header, idx) => {
      row[header] = values[idx] ?? '';
    });

    rows.push(row);
  }

  return rows;
}

function normalizeNumber(raw) {
  const source = String(raw || '').trim();
  if (source === '') return '';

  const cleaned = source.replace(/\$/g, '').replace(/\s/g, '').replace(/,/g, '');
  const parsed = Number(cleaned);
  return Number.isFinite(parsed) ? parsed : '';
}

function normalizeBoolean(raw) {
  const source = String(raw || '').trim().toLowerCase();
  if (!source) return false;
  return ['true', '1', 'si', 'si', 'yes', 'activo'].includes(source);
}

function normalizeJson(raw) {
  const source = String(raw || '').trim();
  if (!source) return null;
  try {
    return JSON.parse(source);
  } catch {
    return source;
  }
}

function coerceValue(raw, type) {
  const t = String(type || '').toUpperCase();
  if (t.includes('BOOLEAN')) return normalizeBoolean(raw);
  if (t.includes('MONEY') || t.includes('DECIMAL') || t.includes('INTEGER')) {
    return normalizeNumber(raw);
  }
  if (t.includes('JSON')) return normalizeJson(raw);
  return raw;
}

function buildTypedRows(schema, tableName, rows) {
  const tableSchema = schema[tableName];
  if (!tableSchema) return rows;

  const typeByColumn = {};
  for (const column of tableSchema.columns || []) {
    typeByColumn[column.name] = column.type;
  }

  return rows.map((row) => {
    const out = {};
    for (const [columnName, raw] of Object.entries(row)) {
      out[columnName] = coerceValue(raw, typeByColumn[columnName]);
    }
    return out;
  });
}

try {
  const schemaSource = fs.readFileSync(schemaPath, 'utf8');
  const schemaObjectLiteral = extractSchemaObjectLiteral(schemaSource);
  const DATA_SCHEMA = Function(`"use strict"; return (${schemaObjectLiteral});`)();

  const files = fs.readdirSync(initDir).filter((name) => name.endsWith('.csv')).sort();
  const tables = {};

  for (const fileName of files) {
    const tableName = path.basename(fileName, '.csv');
    const csvPath = path.join(initDir, fileName);
    const rows = parseCsv(fs.readFileSync(csvPath, 'utf8'));
    tables[tableName] = buildTypedRows(DATA_SCHEMA, tableName, rows);
  }

  const output = `// AUTO-GENERATED by tools/generate_local_init_tables.mjs\n// Source of truth: data/init/*.csv\n\nexport const LOCAL_INIT_TABLES = ${JSON.stringify(tables, null, 2)};\n`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, 'utf8');

  console.log('Generated bundling/generated/localInitTables.js');
  console.log(`Tables: ${Object.keys(tables).length}`);
} catch (error) {
  console.error('Failed to generate local init tables:', error.message);
  process.exit(1);
}
