#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(process.cwd());
const outPath = path.join(root, 'gas', 'Code.gs');

const code = `/**
 * Code.gs - Google Apps Script entry points for claps_codelab_rebuild_components.
 *
 * AUTO-GENERATED by tools/generate_gas_code.mjs
 * DO NOT EDIT MANUALLY - regenerate via: npm run build:gas
 */

function doGet() {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('Cotizador Lodge - Rebuild')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function include(filename) {
  return HtmlService.createHtmlOutputFromFile(filename).getContent();
}

function healthcheck() {
  return {
    ok: true,
    runtime: 'gas',
    at: new Date().toISOString(),
  };
}
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, code, 'utf8');

console.log(`Generated GAS backend entrypoint: ${outPath}`);
